import { BaseHeader } from "../../types/types";
import getRandomValueFromArray from "../array/getRandomValueFromArray";
import rotateAcceptEncodings from "./getRandomAcceptEncoding";
import rotateAcceptLanguage from "./getRandomAcceptLanguage";
import rotateReferer from "./getRandomReferer";

const prebuildBaseHeaders: BaseHeader[] = [
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Lynx: Lynx/2.8.8pre.4 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/2.12.23',
        // 'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
        // 'sec-ch-ua-mobile': '?0',
        // 'sec-ch-ua-platform': 'Windows',
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Wget: Wget/1.15 (linux-gnu)',
        // 'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
        // 'sec-ch-ua-mobile': '?0',
        // 'sec-ch-ua-platform': 'Windows',
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Curl: curl/7.35.0',
        // 'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
        // 'sec-ch-ua-mobile': '?0',
        // 'sec-ch-ua-platform': 'Windows',
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'HTC: Mozilla/5.0 (Linux; Android 7.0; HTC 10 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36',
        'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android 8"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'cache-control': 'no-cache',
        'sec-fetch-site': 'same-origin'
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Google Nexus: Mozilla/5.0 (Linux; U; Android-4.0.3; en-us; Galaxy Nexus Build/IML74K) AppleWebKit/535.7 (KHTML, like Gecko) CrMo/16.0.912.75 Mobile Safari/535.7',
        'sec-ch-ua': '"Not?A_Brand";v="16", "Chromium";v="108", "Google Chrome";v="108"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android 4"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'cache-control': 'no-cache',
        'sec-fetch-site': 'same-origin'
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Samsung Galaxy Note 4: Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N910F Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36',
        'sec-ch-ua': '"Not?A_Brand";v="4", "Chromium";v="108", "Google Chrome";v="108"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android 6"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'cache-control': 'no-cache',
        'sec-fetch-site': 'same-origin'
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Samsung Galaxy Note 3: Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-N900 Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36',
        'sec-ch-ua': '"Not?A_Brand";v="34", "Chromium";v="34", "Google Chrome";v="108"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android 5"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'cache-control': 'no-cache',
        'sec-fetch-site': 'same-origin'
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Samsung Phone: Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G570Y Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36',
        'sec-ch-ua': '"Not?A_Brand";v="44", "Chromium";v="34", "Google Chrome";v="44"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android 6"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'cache-control': 'no-cache',
        'sec-fetch-site': 'same-origin'
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Apple iPhone: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1',
        'sec-ch-ua': '"Apple Inc";v="44", "WebKit";v="34", "Safari";v="44"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"iOS"',
        'sec-fetch-dest': 'empty',
        'cache-control': 'no-cache',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin'
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Apple iPad: Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4',
        'sec-ch-ua': '"Apple Inc";v="44", "WebKit";v="8", "Safari";v="44"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"iOS"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'cache-control': 'no-cache',
        'sec-fetch-site': 'same-origin'
    },
    // TODO Internet explorer and microsoft edge
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76',
        'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Microsoft Edge";v="108"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'cache-control': 'no-cache',
        'device-memory': 8,
        dpr: 1,
        ect: '4g',
        'viewport-width': 1920,
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla Firefox: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0',
        'sec-ch-ua': '"Mozilla Foundation";v="8", "Gecko";v="53", "Firefox";v="53"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'cache-control': 'no-cache',
        'device-memory': 8,
        dpr: 1,
        ect: '4g',
        'viewport-width': 1920,
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0',
        'sec-ch-ua': '"Opera GX";v="93", "Not/A)Brand";v="8", "Chromium";v="107"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'cache-control': 'no-cache',
        'pragma': 'no-cache',
        'device-memory': 8,
        dpr: 1,
        ect: '4g',
        'viewport-width': 1920,
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Google Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
        'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'cache-control': 'no-cache',
        'pragma': 'no-cache',
        'device-memory': 8,
        dpr: 1,
        ect: '4g',
        'viewport-width': 1920,
    },
    {
        Accept: '*/*',
        'Accept-Encoding': rotateAcceptEncodings(),
        'Accept-Language': rotateAcceptLanguage(),
        Referer: rotateReferer(),
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/88.0.4324.152 Safari/537.36',
        'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Brave";v="108"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'cache-control': 'no-cache',
        'pragma': 'no-cache',
        'device-memory': 8,
        dpr: 1,
        ect: '4g',
        'viewport-width': 1920,
    },
];

export const rotatePrebuildHeaders = () => {
    return getRandomValueFromArray(prebuildBaseHeaders);
}

export const getPrebuildHeaderByIndex = (index: number) => {
    return prebuildBaseHeaders[index];
}